#!/usr/bin/python

import rospy, tf
import numpy as np
from math import sqrt, pi
from geometry_msgs.msg import TransformStamped, Pose, Point, PoseStamped, WrenchStamped
from visualization_msgs.msg import Marker
from nav_msgs.msg import Odometry
import tf.transformations as TR

def homogeneous_matrix(trans, quat):
    return TR.concatenate_matrices(TR.translation_matrix(trans), TR.quaternion_matrix(quat))

def quat_from_two_vectors(u_, v_):
    qx = 0.0
    qy = 0.0
    qz = 0.0
    qw = 1.0
    u = u_ / np.linalg.norm(u_)
    v = v_ / np.linalg.norm(v_)

    d = np.dot(u, v)
    if d < 0.99999999 and d > -0.99999999:
        invs = 1.0/sqrt(2.0*(1.0+d))
        xyz = np.cross(u, v*invs)
        qw = 0.5/invs
        qx = xyz[0]
        qy = xyz[1]
        qz = xyz[2]
    elif d < -0.99999999: # infinite number of solutions; picking one
        qw = 0.0
        qx = 1.0
        qy = 0.0
        qz = 0.0
    # else keep identity rotation

    q_norm = np.linalg.norm(np.array([qx, qy, qz, qw]))
    return (qx/q_norm, qy/q_norm, qz/q_norm, qw/q_norm)

class Spoofer(object):
    def __init__(self):
        self.tf_BR             = tf.TransformBroadcaster()

        uavscale = 1.0
        self.uavMarkerPub = rospy.Publisher("uav_marker", Marker, queue_size=1)
        self.uavMarker = Marker()
        self.uavMarker.header.frame_id = "boat"
        self.uavMarker.header.stamp = rospy.Time.now()
        self.uavMarker.id = 1
        self.uavMarker.type = Marker.MESH_RESOURCE
        self.uavMarker.action = Marker.ADD
        self.uavMarker.mesh_resource = "package://uav_dynamics/mesh/quadrotor_bodyaxes.dae"
        self.uavMarker.scale.x = uavscale
        self.uavMarker.scale.y = uavscale
        self.uavMarker.scale.z = uavscale
        self.uavMarker.color.b = 1.0
        self.uavMarker.color.g = 1.0
        self.uavMarker.color.r = 1.0
        self.uavMarker.color.a = 1.0

        arrow_scale = 0.025
        self.fextMarkerPub = rospy.Publisher("fext_marker", Marker, queue_size=1)
        self.fextMarker = Marker()
        self.fextMarker.header.frame_id = "NED"
        self.fextMarker.id = 3
        self.fextMarker.type = Marker.ARROW
        self.fextMarker.action = Marker.ADD
        self.fextMarker.pose = Pose()
        self.fextMarker.pose.position.x = 0.0
        self.fextMarker.pose.position.y = 0.0
        self.fextMarker.pose.position.z = -0.1
        self.fextMarker.scale.x = arrow_scale
        self.fextMarker.scale.y = arrow_scale
        self.fextMarker.scale.z = arrow_scale
        self.fextMarker.color.r = 0.0
        self.fextMarker.color.g = 1.0
        self.fextMarker.color.b = 1.0
        self.fextMarker.color.a = 1.0

        self.Fext_x = 0
        self.Fext_y = 0
        self.Fext_z = 0

        self.odom_sub = rospy.Subscriber("pose", PoseStamped, self.odomCallback)
        self.Fext_sub = rospy.Subscriber("fext", WrenchStamped, self.wrenchCallback)

    def wrenchCallback(self, msg):
        # expressed in NED frame TODO NWU?
        self.Fext_x = msg.wrench.force.x
        self.Fext_y = msg.wrench.force.y
        self.Fext_z = msg.wrench.force.z

    def odomCallback(self, msg):
        # tf from NED to UAV
        self.tf_BR.sendTransform((msg.pose.position.x,
                                  msg.pose.position.y,
                                  msg.pose.position.z),
                                 (msg.pose.orientation.x,
                                  msg.pose.orientation.y,
                                  msg.pose.orientation.z,
                                  msg.pose.orientation.w),
                                 rospy.Time.now(), "UAV", "boat")

        # UAV marker
        self.uavMarker.header.stamp = rospy.Time.now()
        self.uavMarker.pose = msg.pose
        self.uavMarkerPub.publish(self.uavMarker)

        # Fext marker
        F = np.array([self.Fext_x, self.Fext_y, self.Fext_z])
        self.fextMarker.scale.x = np.linalg.norm(F) / 10.0
        q_fext = quat_from_two_vectors(np.array([1.0,0.0,0.0]), F)
        self.fextMarker.pose.position.x = msg.pose.position.x
        self.fextMarker.pose.position.y = msg.pose.position.y
        self.fextMarker.pose.position.z = msg.pose.position.z
        self.fextMarker.pose.orientation.x = q_fext[0]
        self.fextMarker.pose.orientation.y = q_fext[1]
        self.fextMarker.pose.orientation.z = q_fext[2]
        self.fextMarker.pose.orientation.w = q_fext[3]
        self.fextMarker.header.stamp = rospy.Time.now()
        self.fextMarkerPub.publish(self.fextMarker)

def main():
    rospy.init_node("uav_spoofer", anonymous=True)
    es = Spoofer()
    try:
        rospy.spin()
    except KeyboardInterrupt:
        print("Shutting down uav spoofer node")

if __name__ == "__main__":
    main()