#!/usr/bin/env python

import sys

from tuning_gui.plugin import AerowakeTuningPlugin
from rqt_gui.main import Main

plugin = 'tuning_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
